host:
  bridge: br0
  image_dir: /var/lib/libvirt/images
  seed_image:
    source: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  ssh_key: /root/.ssh/id_ed25519
  ip_pool:
    gateway: 192.168.56.2
    dns: 8.8.8.8,8.8.4.4
    ips:
      - 192.168.56.100/24
      - 192.168.56.101/24
      - 192.168.56.102/24

server:
  port: 8080

auth:
  username: admin
  password: admin
